spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  main:
    allow-bean-definition-overriding: true
server:
  port: ${SERVER_PORT:8080}

url:
  frontend: http://localhost:3000/aims-ecommerce
  backend: http://localhost:8080/api/v1

paypal:
  BASE_URL: https://api-m.sandbox.paypal.com
  CLIENT_ID: AY4ClMadd7o0YSd7Ix0vMehoXpUL4pv9SeO_E0Cht6ODzQuZOhl0WkUUR3chtMtDzo7sDGbdW3-RNE_i
  APP_SECRET: EA0DsVkx0L5jmjRmGyfD9W6DhBsodsm54WfFPXd74ntwwE-BAQXAsZiw1KFnSAQXr3cbqfreS5qMx70J